# Generated by Django 5.0.6 on 2024-08-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
