name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t react-cms-web-app-1 .

      - name: Run Tests
        run: docker run --rm react-cms-web-app-1 npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Docker
        run: docker-compose up -d
